export enum KeyboardKey {
  // Teclas de caracteres
  A = "a",
  B = "b",
  C = "c",
  D = "d",
  E = "e",
  F = "f",
  G = "g",
  H = "h",
  I = "i",
  J = "j",
  K = "k",
  L = "l",
  M = "m",
  N = "n",
  O = "o",
  P = "p",
  Q = "q",
  R = "r",
  S = "s",
  T = "t",
  U = "u",
  V = "v",
  W = "w",
  X = "x",
  Y = "y",
  Z = "z",
  Digit0 = "0",
  Digit1 = "1",
  Digit2 = "2",
  Digit3 = "3",
  Digit4 = "4",
  Digit5 = "5",
  Digit6 = "6",
  Digit7 = "7",
  Digit8 = "8",
  Digit9 = "9",
  Exclamation = "!",
  At = "@",
  Hash = "#",
  Dollar = "$",
  Percent = "%",
  Caret = "^",
  Ampersand = "&",
  Asterisk = "*",
  ParenthesisLeft = "(",
  ParenthesisRight = ")",
  Minus = "-",
  Underscore = "_",
  Equal = "=",
  Plus = "+",
  BracketLeft = "[",
  BracketRight = "]",
  BraceLeft = "{",
  BraceRight = "}",
  Backslash = "\\",
  Pipe = "|",
  Semicolon = ";",
  Colon = ":",
  Quote = "'",
  DoubleQuote = '"',
  Comma = ",",
  Period = ".",
  Question = "?",
  Slash = "/",
  LessThan = "<",
  GreaterThan = ">",

  // Teclas de función
  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",
  F11 = "F11",
  F12 = "F12",

  // Teclas de control
  Backspace = "Backspace",
  Tab = "Tab",
  Enter = "Enter",
  Shift = "Shift",
  Control = "Control",
  Alt = "Alt",
  CapsLock = "CapsLock",
  Escape = "Escape",
  Space = " ",
  PageUp = "PageUp",
  PageDown = "PageDown",
  End = "End",
  Home = "Home",
  ArrowLeft = "ArrowLeft",
  ArrowUp = "ArrowUp",
  ArrowRight = "ArrowRight",
  ArrowDown = "ArrowDown",
  Insert = "Insert",
  Delete = "Delete",
  Meta = "Meta",

  // Otras teclas especiales
  Pause = "Pause",
  ScrollLock = "ScrollLock",
  PrintScreen = "PrintScreen",
  NumLock = "NumLock",
  ContextMenu = "ContextMenu",

  // Teclado numérico (Numpad)
  Numpad0 = "Numpad0",
  Numpad1 = "Numpad1",
  Numpad2 = "Numpad2",
  Numpad3 = "Numpad3",
  Numpad4 = "Numpad4",
  Numpad5 = "Numpad5",
  Numpad6 = "Numpad6",
  Numpad7 = "Numpad7",
  Numpad8 = "Numpad8",
  Numpad9 = "Numpad9",
  NumpadMultiply = "NumpadMultiply",
  NumpadAdd = "NumpadAdd",
  NumpadSubtract = "NumpadSubtract",
  NumpadDecimal = "NumpadDecimal",
  NumpadDivide = "NumpadDivide",

  // Modificadores
  ShiftLeft = "Shift",
  ControlLeft = "Control",
  AltLeft = "Alt",
  MetaLeft = "Meta",
}
